name: build gwlbtun

on:
  push:
    branches: [ main ]

jobs:
  build-gwlbtun:
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/amazonlinux/amazonlinux:2023
    steps:
      - name: Setup dnf
        run: |
          dnf -y update
          dnf -y groupinstall "Development Tools"
          dnf -y install cmake gcc-c++ git openssl-devel boost-devel

      - uses: actions/checkout@v4

      - name: Build
        run: |
          git clone https://github.com/aws-samples/aws-gateway-load-balancer-tunnel-handler
          cd aws-gateway-load-balancer-tunnel-handler
          cmake -DCMAKE_BUILD_TYPE=Release .
          make -j"$(nproc)"
          file gwlbtun
          ldd gwlbtun

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gwlbtun-al2023
          path: aws-gateway-load-balancer-tunnel-handler/gwlbtun
